### PR TITLE
Sync Carby with the Gsheet data

### PR DESCRIPTION
**Pull request by Kuraio**
Compared both the Carby data with the GSheet and updated any discrepancies after verifying the data on Angler and TC.
Double checked by Venili Barric [Odin].

### CODE REVIEW

**Review by icykoneko — CHANGES_REQUESTED** [review]
Can you remove the DS file?
The last item, Cloud Kelp doesn’t need to be included since it’s always up.

**Comment by Kuraio** [comment]
We have some fish in there that are always up and are not needed for big fish mooches or ints, e.g. Kholusian King Crab
Still want me to remove it or keep it in there?

DS file, of course.

**Comment by icykoneko** [comment]
Yea, I have Cloud Kelp in my ignored fish list, since it's just for Custom Deliveries.

**Comment by Kuraio** [comment]
Done

**Review by icykoneko — APPROVED** [review]

**Pull request merged**
