### PR TITLE
Dark theme with button

### PR DESCRIPTION
**Pull request by Airex**
Fixed stylish and simple button to change theme

image

### CODE REVIEW

**Comment by icykoneko** [comment]
It's certainly a start, but a couple things I'm not happy with.

* The main table header is invisible in dark mode
* The buttons in the table is still very bright, as are the table rows.

The site is themed using Semantic UI.  They do have templates for generating a dark-mode theme.  That might be a more long term solution.

See if you can at least fix up the table header text.  I'll probably make a branch later to develop a more robust dark theme that addresses the other controls as well.

**Comment by Airex** [comment]
The question about colors is just matter of UI/UX designer vision.

**Comment by Akurosia** [comment]
for body.dark i would suggest to use somthing like "background-color: rgb(40,40,40);" instead of "black" as a pure black is kiinda hard to so over a long time

**Comment by icykoneko** [comment]
Thanks, I'll integrate this shortly.  There's a few touch-ups I need to make sure, so I'll be pulling it into a side-branch first.

**Pull request merged**
